### ISSUE TITLE
em font sizes

### ISSUE THREAD

**Issue by jaro-io** [jeremyharris/split_lines#10]
dear @jeremyharris.
thank you so much for your little plugin. it really helps me a lot.

so far, i have been building my site with fixed font sizes like `px` or `vw`. but i am currently switching to `em` values. the problem is, it breaks your plugin. the clone you create and then append in the first place, has the same class as the original element. so `em` values get multiplied.

for example if my body font size is `16px` and element font size is `2em`, it results in my element having a `32px` font size. the clone however also has the same `2em` applied, so it results in `64px`, having the effect that the lines don't get calculated correctly.

i built a little workaround in which i removed the original class for the clone and changed the tag to a `<p>` element. the last part is needed, because my `h1` or `h2` tags have em values applied as well. so removing the class wouldn't do the trick.

if you have time, it would be lovely to see an improvement of your plugin coming.
again, thank you so much!
jaro

**Comment by jeremyharris** [comment]
I'm glad you like the plugin. Can you post some minimal HTML & CSS that I can use to reproduce the problem. If it's an issue with the child elements inheriting a class that is incompatible, I'm not sure what I can do in the library to fix it, but I can try some things. Ideally, what would you like to see as a fix?

**Comment by jaro-io** [comment]
hm, i cant reproduce with minimal html css now.. its strange. on my site it still doesnt work with the same code. might be something on my end then.. i will investigate and let you know :) thanks for standing by thought <3

**Comment by jeremyharris** [comment]
@jaro-io I'm going to close this issue, but if you come up with a test case please feel free to re-open it!
