### ISSUE TITLE
for...in loop over arrays cause erroneous behavior if array object has been altered

### ISSUE THREAD

**Issue by numasi** [jeremyharris/split_lines#3]
`for (var tagless in splitContent)` on line 43
and
`for (var word in splitContent)` on line 48 
can cause strange behavior if scrip used in conjunction with a polyfill like this one:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#Polyfill

this is due to for...in loops trough methods attached to global Array object as well.

should use exact array indexes like so:
`for (var i = 0; i < splitContent.length; i++)`

avoding for...in loops in Javascript can save us a lot of trouble:
http://stackoverflow.com/questions/500504/why-is-using-for-in-with-array-iteration-a-bad-idea

thank you for the plugin!

**Comment by jeremyharris** [comment]
Thanks for bringing this to my attention! I'll take care of it 😄

**Comment by jeremyharris** [comment]
Sorry about the delay, should all be good now 👍 

Thanks for the report!
