### ISSUE TITLE
width not define - fixing tips

### ISSUE THREAD

**Issue by charlymorfin** [jeremyharris/split_lines#6]
Hi Jeremy,

I want use your nice plugin and I need to use it on an element without any width define.
As it not possible, I have edit the code myself and use the clone function for make the width on the cloned element:

function _createTemp(element) {
	var width = element.width();
	return element.clone().css({position: 'absolute', width: width});
};

As I'm designer and not really good with javascript I think you can probably find a better way to do this.

**Comment by jeremyharris** [comment]
Thanks for the compliments and the report!

I believe this might already be handled. If you take a look at demos 3 and 4, you can see that there is no width defined when calling `.splitLines()`. The children that are split are restricted by the parent element's width, defined in css.

Are you looking for something different? Perhaps you can paste in a small test case (the original html and its css) so I can see what's not working.

**Comment by dongepulango** [comment]
I experience bug that if it has many lines and you don't define the `width` it will not split each line properly. Some `span` has 2 lines instead of one each.

**Comment by dongepulango** [comment]
@jeremyharris here is a codepen for the issue I'm having: https://codepen.io/dongepulango/pen/WawWQy

Now if the plugin is working right, there should be 4 lines, right? I want to make the `<span>` have style of `display: inline-block` so I can animate each line with `transform`. I can't do that if the `<span>`'s are `display: inline`.

I can't specify `width` because I want the text 100% of its container. 

Awesome plugin by the way, thanks. :)

**Comment by jeremyharris** [comment]
@dongepulango thanks for the codepen! I'll try to figure out what's going on and report back :)

**Comment by jeremyharris** [comment]
When either of you get a chance, would you mind checking out PR #7 to see if it solves your issues? Thanks :)

**Comment by jeremyharris** [comment]
Nice, good to hear! I'll leave this and the PR open for a few days to see if we hear back from @charlymorfin.

**Comment by dongepulango** [comment]
After the latest update I'm getting this error:

Uncaught TypeError: Cannot read property 'offsetWidth' of undefined
    at x.fn.init.t.fn.splitLines (jquery.splitlines.js:114)
    at HTMLDocument.<anonymous> (animations.js:3692)
    at c (jquery-3.3.1.js:3534)
    at d (jquery-3.3.1.js:3602)

If I use the file before the update the error disappears, so I think this is related to the auto width update.

**Comment by jeremyharris** [comment]
@dongepulango would you mind opening up a new issue with that information and how to replicate it? I'll take a look
