### ISSUE TITLE
After applying split code, when writing in between line then the exceeded text of that line creates a new line

### ISSUE THREAD

**Issue by kamalali** [jeremyharris/split_lines#8]
After applying split code, when writing in between line then the exceeded text of that line creates a new line.
It should prepend's to next line, but it create's new line.

**Comment by jeremyharris** [comment]
Can you post some code that illustrates the bug?

**Comment by kamalali** [comment]
i am using this library on rich-text-editor, because i need each new line (which creates automatically when text exceed's from page width) in a new paragraph tag.
Now when editing in the upper line, the exceeded text pushed below but it creates a new paragraph. 

i need it to readjust

i am using this code to break the lines

$(".myClass").splitLines({
					tag:'<p>',
					width:803,
					keepHtml: true
				})

**Comment by jeremyharris** [comment]
I'm not sure I have enough to reproduce this yet. 

The example you gave me for configuring splitLines is great, thanks! I'll also need some example text that you are splitting that works, and some example of what you are splitting that does not work (e.g. when you edit the "upper line").

If you can PR a failing example into the `demos.html` file, that would be ideal!

**Comment by jeremyharris** [comment]
Have you come up with an example for me @kamalali?
